program: train.py
method: grid
metric:
  name: val_loss
  goal: minimize
parameters:
  dropout_rate1:
    min: 0.05
    max: 0.95
  dropout_rate2:
    min: 0.05
    max: 0.95
  nb_dense:
    min: 64
    max: 512
  nb_filters1:
    min: 16
    max: 64
  nb_filters2:
    min: 32
    max: 108