program: train.py
method: bayes
project: TS_CAN
metric:
  name: valid_loss
  goal: minimize
parameters:
  lr:
    values: [1e-3,1e-4, 1e-5, 1e-6]
  dropout_rate1:
    min: 0.05
    max: 0.95
  dropout_rate2:
    min: 0.05
    max: 0.95
  nb_filter1:
    values: [16,32,64]
  nb_dense:
    values: [128,256,384,512,640,768]

