program: train.py
method: random
project: TS_CAN
metric:
  name: valid_loss
  goal: minimize
parameters:
  dropout_rate1:
    min: 0.05
    max: 0.95
  dropout_rate2:
    min: 0.05
    max: 0.95
  nb_filter1:
    values: [16,32,48]
  nb_filter2:
    values: [32,64,96]
  nb_dense:
    values: [128,256,384,512]
